spring:
  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/datajpa?&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 10
        show_sql: true

logging.level:
  org.hibernate.SQL: debug